version: '3.9'

services:
  screening-client:
    build: .
    restart: on-failure
    ports:
      - 3001:80
    env_file:
      - .env
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M
    ulimits:
      nofile:
        soft: 131072
        hard: 131072

networks:
  backend:
    name: api_default
    external: true

