import { Translations } from './translations';

export enum SourceDescription {
  senat = 'Senat',
  guvern = 'Guvern',
  camera_deputatilor = 'Camera Deputatilor',
  camera_deputatilor_pl = 'Camera Deputatilor PL-X',
  mfinante = 'Ministerul Finantelor',
  mmediu = 'Ministerul Mediului',
  mdezvoltarii = 'Ministerul Dezvoltarii',
  meducatiei = 'Ministerul Educatiei',
  mtransport = 'Ministerul Transporturilor',
  mjustitie = 'Ministerul Justitiei',
  mae = 'Ministerul Afacerilor Externe',
  mai = 'Ministerul Afacerilor Interne',
  mapn = 'Ministerul Apararii Nationale',
  magriculturii = 'Ministerul Agriculturii',
  mcercetarii = 'Ministerul Cercetarii',
  mculturii = 'Ministerul Culturii',
  meconomiei = 'Ministerul Economiei',
  menergiei = 'Ministerul Energiei',
  mfamiliei = 'Ministerul Familiei',
  minvestitiilor = 'Ministerul Investitiilor',
  mmuncii = 'Ministerul Muncii',
  msanatatii = 'Ministerul Sanatatii',
  msport = 'Ministerul Sportului',
  mturism = 'Ministerul Turismului',
}

export const sources = [
  'camera_deputatilor',
  'mfinante',
  'mmediu',
  'mdezvoltarii',
  'meducatiei',
  'mtransport',
  'mai',
  'mae',
  'mapn',
  'mjustitie',
  'senat_pl',
  'camera_deputatilor_pl',
  'magriculturii',
  'mcercetarii',
  'mculturii',
  'meconomiei',
  'menergiei',
  'mfamiliei',
  'minvestitiilor',
  'mmuncii',
  'msanatatii',
  'msport',
  'mturism',
];

export const translatedSources = sources.map((source) => Translations[source]);
